"""
Pair Bipath Collection

This module provides functions for collecting bipath instances for sample pairs.
It handles path exploration from specific pairs and bipath assembly using top K
reliable path types.

Key Functions:
- _explore_paths_for_pair_hop: Explore paths for a single hop from sample pairs
- generate_bipaths_for_pairs: Generate bipath instances for given sample pairs
"""

import logging
from pyspark.sql import functions as F
from pyspark.sql import DataFrame

from joinminer.spark.io import read_table, write_table
from joinminer.spark.io.partition import parse_partition_spec
from joinminer.spark.operations.sample import random_sample
from joinminer.graph.join_edges.bipath_types import extract_u_explore_paths, extract_v_explore_paths
from joinminer.graph.join_edges.add_path import add_path_to_path, add_path_types_to_path, _get_path_type_columns
from joinminer.graph.join_edges.bipath import _transform_backward_path

# Module-level logger
logger = logging.getLogger("joinminer")


def _generate_seed_nodes_for_pairs(
    spark_ctx,
    sample_pairs_df: DataFrame,
    graph,
    bilink_config: dict,
    exploration_base_path: str
) -> None:
    """
    Generate and save hop_0 seed nodes from sample pairs.

    Creates both forward (from u_node) and backward (from v_node) seed nodes
    with pair tracking columns for bipath assembly. Handles the complete lifecycle:
    completion check, generation, persistence, saving, and cleanup.

    Args:
        spark_ctx: Spark context with table_state and persist_manager
        sample_pairs_df: DataFrame with sample pairs (u_node_id, v_node_id, partition columns)
        graph: Graph instance with schema information
        bilink_config: BiLink configuration dictionary
        exploration_base_path: Base path for exploration results (seed nodes saved to hop_0 subdirectory)
    """
    hop_0_path = f"{exploration_base_path}/hop_0"

    # Check if seed nodes are already generated
    is_complete, _ = spark_ctx.table_state.check_complete(hop_0_path)

    if is_complete:
        logger.info(f"Seed nodes already generated at {hop_0_path}, skipping")
        return

    logger.info("Generating seed nodes from sample pairs...")

    # Get node types from target_edge config
    u_node_type = bilink_config['target_edge']['u_node_type']
    v_node_type = bilink_config['target_edge']['v_node_type']
    u_node_type_index = graph.nodes[u_node_type]['type_index']
    v_node_type_index = graph.nodes[v_node_type]['type_index']

    # Forward seed nodes (from unique u_nodes)
    u_seed_nodes = sample_pairs_df.select(
        F.col('u_node_id').alias('node_0_id'),
        F.lit(u_node_type_index).alias('node_0_type'),
        F.lit(0).alias('seed_node_side'),  # u_node = 0
        *[F.col(c) for c in graph.partition_columns]
    ).distinct()

    # Backward seed nodes (from unique v_nodes)
    v_seed_nodes = sample_pairs_df.select(
        F.col('v_node_id').alias('node_0_id'),
        F.lit(v_node_type_index).alias('node_0_type'),
        F.lit(1).alias('seed_node_side'),  # v_node = 1
        *[F.col(c) for c in graph.partition_columns]
    ).distinct()

    # Combine both seed nodes
    seed_nodes = u_seed_nodes.union(v_seed_nodes)

    # Save seed nodes to hop_0
    logger.info(f"Saving seed nodes to: {hop_0_path}")
    write_table(
        spark_ctx,
        seed_nodes,
        hop_0_path,
        partition_columns=['seed_node_side'],
        mode='overwrite'
    )

    # Mark as complete
    spark_ctx.table_state.mark_complete(hop_0_path)
    logger.info(f"Seed nodes saved successfully")


def _explore_paths_for_pair_hop(
    spark_ctx,
    hop_k: int,
    target_paths_df: DataFrame,
    outer_edges_df: DataFrame,
    bilink_config: dict,
    graph,
    exploration_base_path: str,
    max_hop: int,
    explore_hop: int
) -> None:
    """
    Explore paths for a single hop starting from parent paths.

    This function explores paths by joining parent paths with outer edges.
    It handles both forward (from u_node) and backward (from v_node) exploration.
    Includes completion checking and path type extraction.

    Args:
        spark_ctx: Spark context instance
        hop_k: Current hop number (1, 2, 3, ...) - must be >= 1
        target_paths_df: DataFrame containing all target path types
        outer_edges_df: Pre-persisted outer join edges
        bilink_config: BiLink configuration dictionary
        graph: Graph instance with schema information
        exploration_base_path: Base path for exploration results
        max_hop: Maximum hop number from target paths
        explore_hop: Exploration hop depth (middle point of bipaths)

    Note:
        Parent paths are read from hop_{hop_k-1}. For hop_k=1, this reads from hop_0
        which contains seed nodes generated by _generate_seed_nodes_for_pairs.
    """
    hop_output_path = f"{exploration_base_path}/hop_{hop_k}"
    logger.info(f"\n--- Exploring paths for hop {hop_k} ---")

    # Check if already completed
    is_complete, _ = spark_ctx.table_state.check_complete(hop_output_path)
    if is_complete:
        logger.info(f"  Paths for hop {hop_k} already explored at {hop_output_path}, skipping")
        return

    # Extract path specifications for this hop
    logger.info(f"  Extracting path type specifications...")
    u_paths_df = extract_u_explore_paths(target_paths_df, hop_k)

    spark_ctx.persist_manager.persist(
        u_paths_df,
        release_point=f'hop_{hop_k}_done',
        name=f'u_paths_df_hop_{hop_k}'
    )

    u_paths_count = u_paths_df.count()
    logger.info(f"  Forward (u_node) paths: {u_paths_count}")
    if u_paths_count > 0:
        logger.info("  Sample u_node paths:")
        u_paths_df.show(3, truncate=False)

    if 2 * hop_k <= max_hop:
        v_paths_df = extract_v_explore_paths(target_paths_df, hop_k, max_hop)

        spark_ctx.persist_manager.persist(
            v_paths_df,
            release_point=f'hop_{hop_k}_done',
            name=f'v_paths_df_hop_{hop_k}'
        )

        v_paths_count = v_paths_df.count()
        logger.info(f"  Backward (v_node) paths: {v_paths_count}")
        if v_paths_count > 0:
            logger.info("  Sample v_node paths:")
            v_paths_df.show(3, truncate=False)

        explore_path_df = u_paths_df.union(v_paths_df).coalesce(1)

        spark_ctx.persist_manager.persist(
            explore_path_df,
            release_point=f'hop_{hop_k}_done',
            name=f'explore_paths_df_hop_{hop_k}'
        )
    else:
        explore_path_df = u_paths_df

    # Step 1: Read parent paths from previous hop
    parent_path = f"{exploration_base_path}/hop_{hop_k-1}"
    logger.info(f"  Reading parent paths from: {parent_path}")

    if hop_k == explore_hop and max_hop % 2 == 1:
        # Special case: last hop with odd max_hop, only read forward paths
        logger.info("  Reading only forward paths (last hop with odd max_hop)")
        parent_df = read_table(
            spark_ctx,
            parent_path,
            partition_columns=['seed_node_side'],
            partition_instances=[[0]]
        )
    else:
        # Default case: read both directions for bidirectional exploration
        parent_df = read_table(
            spark_ctx,
            parent_path
        )

    # Add path type specifications
    parent_df = add_path_types_to_path(
        path_df=parent_df,
        path_type_df=explore_path_df,
        path_length=hop_k - 1,
        additional_join_columns=['seed_node_side']
    )
    logger.info("  Path types added and parent paths filtered")

    # Step 2: Transform outer edges for joining
    logger.info("  Transforming outer edges for joining...")

    join_edge_transformed = outer_edges_df.select(
        F.col('join_node_id').alias(f'node_{hop_k-1}_id'),
        F.col('add_node_id').alias(f'node_{hop_k}_id'),
        F.col('join_node_type').alias(f'node_{hop_k-1}_type'),
        F.col('add_node_type').alias(f'node_{hop_k}_type'),
        F.col('edge_type').alias(f'edge_{hop_k-1}_type'),
        F.when(F.col('join_node_side') == 0, F.lit(hop_k-1))
         .otherwise(F.lit(hop_k))
         .alias(f'u_index_of_edge_{hop_k-1}'),
        F.when(F.col('join_node_side') == 1, F.lit(hop_k-1))
         .otherwise(F.lit(hop_k))
         .alias(f'v_index_of_edge_{hop_k-1}'),
        *[F.col(c) for c in graph.partition_columns]
    )

    # Step 3: Join parent paths with edges
    join_columns = [
        f'node_{hop_k-1}_id',
        f'node_{hop_k-1}_type',
        f'edge_{hop_k-1}_type',
        f'u_index_of_edge_{hop_k-1}',
        f'v_index_of_edge_{hop_k-1}',
        f'node_{hop_k}_type',
    ] + graph.partition_columns

    if hop_k == 1:
        # Direct join for first hop
        logger.info("  Joining seed nodes with first edges (direct join)...")
        result_df = parent_df.join(
            join_edge_transformed,
            on=join_columns,
            how='inner'
        )

    else:
        # Use add_path_to_path for deduplication
        logger.info("  Using add_path_to_path with duplicate edge prevention...")

        path_df = add_path_to_path(
            spark_ctx=spark_ctx,
            left_path_df=parent_df,
            right_path_df=join_edge_transformed,
            join_columns=join_columns,
            left_hop_k=hop_k - 1,
            right_hop_k=1,
            release_point=f'hop_{hop_k}_done',
            skew_threshold=1000,
            salt_buckets=100
        )

        # Sample paths to control explosion
        logger.info("  Sampling paths to control explosion...")
        max_instance = bilink_config['bipath_discovery']['max_instance']

        group_columns = [
            'node_0_id', 'node_0_type', 'seed_node_side',
            *[f'edge_{i}_type' for i in range(hop_k)],
            *[f'u_index_of_edge_{i}' for i in range(hop_k)],
            *[f'v_index_of_edge_{i}' for i in range(hop_k)]
        ] + graph.partition_columns

        result_df = random_sample(path_df, group_columns, max_instance)

    # Step 4: Write results
    logger.info(f"  Writing results to: {hop_output_path}")
    write_table(
        spark_ctx,
        result_df,
        hop_output_path,
        partition_columns=['seed_node_side'],
        mode='overwrite'
    )

    # Mark as complete
    spark_ctx.table_state.mark_complete(hop_output_path)
    logger.info(f"  Hop {hop_k} exploration completed successfully")

    # Release per-hop DataFrames
    spark_ctx.persist_manager.mark_released(f'hop_{hop_k}_done')


def _compute_hop_k_bipaths_for_pairs(
    spark_ctx,
    hop_k: int,
    forward_hop_k: int,
    backward_hop_k: int,
    hop_paths_df: DataFrame,
    unique_pairs_df: DataFrame,
    exploration_base_path: str,
    output_path: str,
    max_instance: int,
    partition_columns: list
) -> None:
    """
    Compute and save bipath instances for a single hop.

    This function encapsulates the bipath assembly logic for one hop:
    1. Reads forward paths from exploration/hop_{forward_hop_k}/seed_node_side=0
    2. Reads backward paths from exploration/hop_{backward_hop_k}/seed_node_side=1
    3. Transforms backward paths using _transform_backward_path from bipath.py
    4. Joins forward and backward paths at intersection node
    5. Filters to pairs present in unique_pairs_df
    6. Saves directly to {output_path}/bipaths/hop_{hop_k}

    Args:
        spark_ctx: Spark context with persist_manager and table_state
        hop_k: Total bipath length
        forward_hop_k: Number of forward hops
        backward_hop_k: Number of backward hops
        hop_paths_df: DataFrame with target path types for this hop (filtered by hop_k)
        unique_pairs_df: DataFrame with unique (u_node_id, v_node_id, partition columns)
        exploration_base_path: Base path for exploration results
        output_path: Base output path for bipaths
        max_instance: Maximum bipath instances per group for sampling
        partition_columns: Graph partition columns (e.g., ['date'])

    Note:
        Maintains naming convention: node_0_id (u_node), node_{hop_k}_id (v_node)
        Saves directly to disk without returning DataFrame
    """
    hop_output_path = f"{output_path}/bipaths/hop_{hop_k}"

    # Check if already completed
    is_complete, _ = spark_ctx.table_state.check_complete(hop_output_path)
    if is_complete:
        logger.info(f"  Bipaths for hop {hop_k} already computed at {hop_output_path}, skipping")
        return

    logger.info(f"  Computing bipaths for hop {hop_k}...")
    logger.info(f"    Forward hop: {forward_hop_k}, Backward hop: {backward_hop_k}")

    # Define release point for this hop
    release_point = f'bipath_hop_{hop_k}_assembly'

    # Read forward paths from exploration results
    forward_path = f"{exploration_base_path}/hop_{forward_hop_k}/seed_node_side=0"
    logger.info(f"    Reading forward paths from: {forward_path}/seed_node_side=0")
    forward_paths_df = read_table(
        spark_ctx,
        forward_path
    )

    # Read backward paths from exploration results
    backward_path = f"{exploration_base_path}/hop_{backward_hop_k}/seed_node_side=1"
    logger.info(f"    Reading backward paths from: {backward_path}/seed_node_side=1")
    backward_paths_df = read_table(
        spark_ctx,
        backward_path
    )

    # Transform backward paths using bipath.py helper function
    logger.info("    Transforming backward paths to align with bipath schema...")
    backward_paths_df = _transform_backward_path(
        spark_ctx=spark_ctx,
        backward_path_df=backward_paths_df,
        forward_hop_k=forward_hop_k,
        backward_hop_k=backward_hop_k,
        partition_columns=partition_columns,
        max_instance=max_instance,
        release_point=release_point
    )

    # OPTIMIZATION: Add target node constraint before expensive join
    # Step 1: Rename unique_pairs columns to match bipath schema
    logger.info("    Preparing unique pairs with renamed columns...")
    renamed_pairs_df = unique_pairs_df.select(
        F.col('u_node_id').alias('node_0_id'),
        F.col('v_node_id').alias(f'node_{hop_k}_id'),
        *[F.col(c) for c in partition_columns]
    )

    # Step 2: Join forward paths with renamed pairs to add target node_{hop_k}_id
    logger.info("    Adding target node constraint to forward paths...")
    forward_with_target_df = forward_paths_df.join(
        renamed_pairs_df,
        on=['node_0_id'] + partition_columns,
        how='inner'
    )

    # Step 2.5: Add backward path type specifications to forward paths
    logger.info("    Adding backward path type specifications to forward paths...")
    # Filter columns before passing to add_path_types_to_path
    path_type_columns = _get_path_type_columns(hop_k)
    hop_paths_df_filtered = hop_paths_df.select(*path_type_columns)

    forward_with_target_df = add_path_types_to_path(
        path_df=forward_with_target_df,
        path_type_df=hop_paths_df_filtered,
        path_length=forward_hop_k,
        additional_join_columns=[]
    )

    # Step 3: Join forward and backward paths using add_path_to_path
    logger.info("    Joining forward and backward paths with target constraint...")

    # Build join columns: intersection node, target node, backward path types, and partition columns
    join_columns = [
        f'node_{forward_hop_k}_id',
        f'node_{forward_hop_k}_type',
        f'node_{hop_k}_id'  # Target node constraint (key optimization)
    ]
    # Add backward path type columns (edge types and node types)
    for i in range(forward_hop_k, hop_k):
        join_columns.extend([
            f'edge_{i}_type',
            f'u_index_of_edge_{i}',
            f'v_index_of_edge_{i}'
        ])
    for i in range(forward_hop_k + 1, hop_k + 1):
        join_columns.append(f'node_{i}_type')
    # Add partition columns
    join_columns.extend(partition_columns)

    bipath_df = add_path_to_path(
        spark_ctx=spark_ctx,
        left_path_df=forward_with_target_df,
        right_path_df=backward_paths_df,
        join_columns=join_columns,
        left_hop_k=forward_hop_k,
        right_hop_k=backward_hop_k,
        release_point=release_point,
        skew_threshold=1000,  # Deprecated but kept for compatibility
        salt_buckets=100  # Deprecated but kept for compatibility
    )

    # Save directly to hop-specific output path
    logger.info(f"    Saving bipaths to: {hop_output_path}")
    write_table(
        spark_ctx,
        bipath_df,
        hop_output_path,
        mode='overwrite'
    )

    # Mark as complete
    spark_ctx.table_state.mark_complete(hop_output_path)
    logger.info(f"  Hop {hop_k} bipath assembly completed successfully")

    # Release persisted DataFrames for this hop
    spark_ctx.persist_manager.mark_released(release_point)


def generate_bipaths_for_pairs(spark_ctx, bilink_config, graph, target_paths_df,
                               unique_pairs_df, max_hop, explore_hop,
                               output_path, bipath_dates):
    """
    Generate bipath instances for sample pairs using top K reliable path types.

    Args:
        spark_ctx: Spark context
        bilink_config: BiLink configuration
        graph: Graph instance
        target_paths_df: Pre-computed target paths DataFrame
        unique_pairs_df: Unique pairs DataFrame (u_node_id, v_node_id, partition columns)
        max_hop: Maximum hop number
        explore_hop: Exploration hop depth
        output_path: Output path for collected bipaths
        bipath_dates: List of target dates for bipath collection (for filtering outer edges)
    """
    logger.info("\n" + "="*70)
    logger.info(f"Generating bipaths for pairs")
    logger.info(f"  Output base: {output_path}")
    logger.info("="*70)

    # Check if bipaths are already complete
    bipaths_output_path = f"{output_path}/bipaths"
    is_complete, _ = spark_ctx.table_state.check_complete(bipaths_output_path)

    if is_complete:
        logger.info(f"Bipaths already complete at {bipaths_output_path}, skipping")
        return

    # Phase 2: Read and prepare outer edges
    logger.info(f"\nPhase 2: Load outer join edges")
    logger.info("-"*70)

    # Convert bipath_dates to partition format
    date_partitions = parse_partition_spec(
        partition_columns=graph.partition_columns,
        partition_spec=bipath_dates
    )

    logger.info(f"Loading outer edges for {len(date_partitions)} date partition(s)")

    join_edge_path = bilink_config['bipath_discovery']['join_edge_path']
    logger.info(f"Reading outer join edges from: {join_edge_path}/outer")

    outer_edges_df = read_table(
        spark_ctx,
        f"{join_edge_path}/outer",
        partition_columns=graph.partition_columns,
        partition_instances=date_partitions
    )

    spark_ctx.persist_manager.persist(
        outer_edges_df,
        release_point='exploration_done',
        name='outer_edges_df'
    )

    # Phase 3: Generate hop_0 seed nodes
    logger.info(f"\nPhase 4: Generate hop_0 seed nodes")
    logger.info("-"*70)

    # Store exploration results in subdirectory
    exploration_base_path = f"{output_path}/path_exploration"

    # Generate and save seed nodes (handles everything internally)
    _generate_seed_nodes_for_pairs(
        spark_ctx=spark_ctx,
        sample_pairs_df=unique_pairs_df,
        graph=graph,
        bilink_config=bilink_config,
        exploration_base_path=exploration_base_path
    )

    # Phase 4: Explore paths from sample pairs
    logger.info(f"\nPhase 4: Explore paths from sample pairs")
    logger.info("-"*70)

    for hop_k in range(1, explore_hop + 1):
        # Explore paths for this hop (handles path extraction, completion checking, and cleanup internally)
        # For hop_k=1, reads hop_0 seed nodes; for hop_k>=2, reads previous hop
        _explore_paths_for_pair_hop(
            spark_ctx=spark_ctx,
            hop_k=hop_k,
            target_paths_df=target_paths_df,
            outer_edges_df=outer_edges_df,
            bilink_config=bilink_config,
            graph=graph,
            exploration_base_path=exploration_base_path,
            max_hop=max_hop,
            explore_hop=explore_hop
        )

    # Release outer_edges_df after exploration is complete
    spark_ctx.persist_manager.mark_released('exploration_done')
    logger.info("Outer edges released after exploration")

    # Phase 5: Assemble and save bipaths
    logger.info(f"\nPhase 5: Assemble and save bipaths")
    logger.info("-"*70)

    for hop_k in range(1, max_hop + 1):
        logger.info(f"\n--- Processing hop {hop_k}/{max_hop} ---")

        # Filter target paths for this hop
        hop_paths_df = target_paths_df.filter(F.col('hop_k') == hop_k)

        if hop_paths_df.count() == 0:
            logger.info(f"  No paths for hop {hop_k}, skipping")
            continue

        # Calculate forward and backward hop splits
        forward_hop_k = (hop_k + 1) // 2
        backward_hop_k = hop_k - forward_hop_k

        # Compute and save bipaths for this hop using helper function
        _compute_hop_k_bipaths_for_pairs(
            spark_ctx=spark_ctx,
            hop_k=hop_k,
            forward_hop_k=forward_hop_k,
            backward_hop_k=backward_hop_k,
            hop_paths_df=hop_paths_df,
            unique_pairs_df=unique_pairs_df,
            exploration_base_path=exploration_base_path,
            output_path=output_path,
            max_instance=bilink_config['bipath_discovery']['max_instance'],
            partition_columns=graph.partition_columns
        )

    # Mark entire bipaths directory as complete
    spark_ctx.table_state.mark_complete(bipaths_output_path)
    logger.info(f"\nAll bipaths saved successfully to: {bipaths_output_path}")
